### ISSUE TITLE
MQTT passwords can be also alphanumeric (here only integers are sent)

### ISSUE THREAD

**Issue by dennisheitmann** [rkubera/ESP8266-MQTT-to-Serial-Bridge#1]
https://github.com/rkubera/ESP8266-MQTT-to-Serial-Bridge/blob/7d753173c6a9ba9e45dc97cd7ff4399a61b54366/commands.ino#L143

I would remove .toInt()

`mqtt_pass = payload.substring(tmpIdx+1);`

**Comment by rkubera** [comment]
Thank you for your bug fix.
Added to master.
Regards, Radek.
